server:
  port: 8081

#####  spring configuration
spring:
  datasource:
    #MySQL configuration
    username: root
    password: root
    url: jdbc:mysql://192.168.20.10:3306/workOnline
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: DateWorkOnline
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      #30min
      max-lifetime: 1800000
      #30s
      connection-timeout: 30000
      connection-test-query: SELECT 1
  #spring cloud configuration
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: server


#####   mybatis-plus configuration
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      #      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


logging:
  level:
    com.gkhy.gulimall: debug
